import Head from 'next/head'
import Navbar from '../components/Navbar'
import Homepage from '../components/Homepage'
import Services from '../components/Services'
import Portfolio from '../components/Portfolio'
import Section from '../components/Section'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Green Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Homepage />
      <Services />
      <Portfolio />
      <Section />
      <Contact />

    </div>
  )
}
